version: '3.7'
services:
  riak:
    image: basho/riak-kv:ubuntu-2.2.3
    ports:
      - 8087
      - 8098
    volumes:
      - ./etc/riak/user.conf:/etc/riak/user.conf
    deploy:
      mode: replicated
      replicas: 3
