---
- name: Configure Riak cluster
  hosts: riak
  become: true

  tasks:
    - include: configure-riak-cluster_2x.yml
      when: "riak_version is version('3.0.0', '<', version_type='semver')"

    - include: configure-riak-cluster_3x.yml
      when: "riak_version is version('3.0.0', '>=', version_type='semver')"
