---
- name: Install and configure Riak
  hosts: riak
  become: true

  tasks:
    - set_fact:
        riak_version_xyz: "{{ riak_version | regex_replace('^([0-9]+)\\.([0-9]+)\\.([0-9]+).*$', '\\1.\\2.\\3') }}"
    - set_fact:
        riak_version_xy: "{{ riak_version | regex_replace('^([0-9]+)\\.([0-9]+)\\.([0-9]+).*$', '\\1.\\2') }}"

    - name: Download Riak
      get_url:
        url: https://files.tiot.jp/riak/kv/{{ riak_version_xy }}/{{ riak_version_xyz }}/ubuntu/focal64/riak_{{ riak_version }}_amd64.deb
        dest: /tmp/riak_{{ riak_version }}_amd64.deb

    - name: Install Riak
      apt:
        deb: /tmp/riak_{{ riak_version }}_amd64.deb
        state: present

    - name: Configure node name
      lineinfile:
        path: /etc/riak/riak.conf
        line: "nodename = riak@{{ ansible_host }}"
        regexp: "^nodename ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure storage backend
      lineinfile:
        path: /etc/riak/riak.conf
        line: "storage_backend = {{ riak_storage_backend }}"
        regexp: "^storage_backend ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure ring size
      lineinfile:
        path: /etc/riak/riak.conf
        line: "ring_size = {{ riak_ring_size }}"
        regexp: "^ring_size ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure protobuf interface
      lineinfile:
        path: /etc/riak/riak.conf
        line: "listener.protobuf.internal = {{ ansible_host }}:8087"
        regexp: "^listener.protobuf.internal ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure HTTP interface
      lineinfile:
        path: /etc/riak/riak.conf
        line: "listener.http.internal = {{ ansible_host }}:8098"
        regexp: "^listener.http.internal ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure Erlang distribution port range (minimum)
      lineinfile:
        path: /etc/riak/riak.conf
        line: "erlang.distribution.port_range.minimum = 6000"
        regexp: "^erlang.distribution.port_range.minimum ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure Erlang distribution port range (maximum)
      lineinfile:
        path: /etc/riak/riak.conf
        line: "erlang.distribution.port_range.maximum = 7023"
        regexp: "^erlang.distribution.port_range.maximum ="
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Disable Riak Control
      replace:
        path: /etc/riak/riak.conf
        regexp: '^riak_control(.*)'
        replace: '#riak_control\1'

    - name: Configure ulimit (soft) in /etc/security/limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: "riak soft nofile 65536"
        regexp: "^riak soft nofile"
        create: yes
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak
    - name: Configure ulimit (hard) in /etc/security/limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: "riak hard nofile 262144"
        regexp: "^riak hard nofile"
        create: yes
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure ulimit in /etc/default/riak
      lineinfile:
        path: /etc/default/riak
        line: "ulimit -n 262144"
        regexp: "^ulimit -n"
        create: yes
      notify:
        - Stop Riak
        - Re-initialize Riak
        - Start Riak

    - name: Configure ulimit in /lib/systemd/system/riak.service
      community.general.ini_file:
        path: /lib/systemd/system/riak.service
        section: Service
        option: LimitNOFILE
        value: infinity

    - name: Ensure Riak is running
      ansible.builtin.service:
        name: riak
        state: started

  handlers:
    - name: Stop Riak
      ansible.builtin.service:
        name: riak
        state: stopped

    - name: Re-initialize Riak
      shell: |
        rm -rf /var/lib/riak/*

    - name: Start Riak
      ansible.builtin.service:
        name: riak
        state: started
