---
- name: Install and configure YCSB
  hosts: ycsb
  become: true

  tasks:
    - name: Install Java 8 JRE
      become: true
      apt:
        name: openjdk-8-jre
        update_cache: yes

    - name: Install Python
      become: true
      apt:
        name: python
        update_cache: yes

    - name: Download YCSB
      get_url:
        url: https://github.com/brianfrankcooper/YCSB/releases/download/{{ ycsb_version }}/ycsb-{{ ycsb_version }}.tar.gz
        dest: /tmp/ycsb-{{ ycsb_version }}.tar.gz

    - name: Create /opt/ycsb directory if it does not exist
      ansible.builtin.file:
        path: /opt/ycsb
        state: directory

    - name: Extract YCSB into /opt/ycsb/
      ansible.builtin.unarchive:
        remote_src: yes
        src: /tmp/ycsb-{{ ycsb_version }}.tar.gz
        dest: /opt/ycsb
        extra_opts:
        - --strip-components=1
